import fs from 'node:fs';
const html=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('styles.css','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const app=fs.readFileSync('app.js','utf8');
const assert=(c,m)=>{if(!c){console.error('UI/OFFLINE TEST FAILED:',m);process.exit(1)}};

assert(!html.includes('saveBtn'),'approved concept must not contain a save button');
assert(!html.includes('screen-materials'),'materials screen must stay removed');
assert((html.match(/class="dock-item/g)||[]).length===2,'dock must have exactly two items');
assert(/\.dock\{[^}]*position:fixed/i.test(css),'dock must be fixed');
assert(/\.dock\{[^}]*left:50%/i.test(css),'dock left must be 50%');
assert(/\.dock\{[^}]*transform:translateX\(-50%\)/i.test(css),'dock must use translateX(-50%)');
assert(/\.dock\{[^}]*bottom:2px/i.test(css),'dock bottom must be 2px');
assert(/\.dock\{[^}]*width:87%/i.test(css),'dock width must be 87%');
assert(/\.dock\{[^}]*height:68px/i.test(css),'dock height must be 68px');
assert(!/\.dock\{[^}]*safe-area/i.test(css),'dock must not depend on safe area');
assert(/\.app-shell\{[^}]*min-height:100dvh/i.test(css),'app shell must use 100dvh');
assert(css.includes('var(--safe-bottom)'),'safe area must reserve content only');
assert(/\.result-value strong\{[^}]*font-size:39px/i.test(css),'result typography must match compact concept');
assert(/\.bar-details summary\{[^}]*height:44px/i.test(css),'bar summary must be compact');
assert(!css.includes('!important'),'clean rebuild must not use override patches');
assert(!/https?:\/\//i.test(html+css+app),'runtime UI must not depend on remote resources');
assert(app.includes('saveSnapshot'),'history must persist valid calculations without a save button');
assert(sw.includes("const VERSION='2.2.0'"),'offline cache must be versioned');
assert(sw.includes("'./assets/result-rod.webp'"),'result WebP must be precached');
assert(sw.includes('cache.addAll(APP_SHELL)'),'offline shell must cache atomically');
assert(!sw.includes('networkFirst'),'offline shell must not be network-first');
console.log('UI and offline contract OK');